# Generated by Django 2.2.5 on 2019-10-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('road_building', 'Road building'), ('year_of_plenty', 'Year of plenty'), ('monopoly', 'Monopoly'), ('victory_point', 'Victory point'), ('knight', 'Knight')], max_length=30)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
