# Generated by Django 2.2.5 on 2019-10-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=100)),
                ('resource', models.CharField(default='', max_length=100)),
                ('token', models.IntegerField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VertexPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
    ]
