# Generated by Django 2.2.5 on 2019-10-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hex',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
