# Generated by Django 2.2.5 on 2019-10-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191003_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hex',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.VertexPosition'),
        ),
    ]
