# Generated by Django 2.2.5 on 2019-10-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20191004_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='hex',
            name='game',
            field=models.IntegerField(default=0),
        ),
    ]
