# Generated by Django 2.2.5 on 2019-10-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20191004_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertexposition',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vertexposition',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
