# Generated by Django 2.2.5 on 2019-10-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20191004_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hex',
            name='resource',
            field=models.CharField(choices=[('WOOL', 'Wool'), ('LUMBER', 'Lumber'), ('BRICK', 'Brick'), ('GRAIN', 'Grain'), ('ORE', 'Ore'), ('NOTHING', 'Nothing')], default='NO', max_length=7),
        ),
    ]
