test:pylint:
    image: python:3.6
    script:
        - pip install pycodestyle
        - pycodestyle --exclude='migrations*, settings*' .

test:unittest:
    image: python:3.6
    script:
        - pip install -r requirements.txt
        - cd catan/
        - python manage.py makemigrations card catan game lobby player resource
        - python manage.py migrate 
        - python manage.py test
