test:pylint:
    image: python:3.6

    before_script:
        - pip install -r requirements/requirements.txt

    script:
        - pip install pylint --quiet
        - pylint --ignored-classes=_socketobject *.py
