# Generated by Django 2.2.5 on 2019-10-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_hex_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hex',
            name='token',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
