# Generated by Django 2.2.5 on 2019-10-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20191004_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hex',
            old_name='game',
            new_name='game_id',
        ),
    ]
