# Generated by Django 2.2.5 on 2019-10-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20191004_0038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hex',
            unique_together={('game_id', 'position')},
        ),
    ]
