# Generated by Django 2.2.5 on 2019-10-08 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_auto_20191008_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='room_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
