# Generated by Django 2.2.5 on 2019-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_auto_20191008_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
